name: Deploy React App on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print secrets (masked by GitHub)
        run: |
          echo "EC2_HOST = '${{ secrets.EC2_HOST }}'"
          echo "EC2_USER = '${{ secrets.EC2_USER }}'"
          echo "EC2_SSH_KEY = '${{ secrets.EC2_SSH_KEY }}'"
          
      - name: Deploy via SSH to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "Go to project directory"
            cd ~/react-app/react-frontend

            echo "Pull latest code"
            git pull origin main

            echo "Install dependencies"
            npm ci

            echo "Build Vite app"
            npm run build

            echo "Deploy dist to Nginx root"
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/

            echo "Fix permissions"
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html

            echo "Reload Nginx"
            sudo systemctl reload nginx
